"""add profile fields to user

Revision ID: d78dfff32aa3
Revises: add_is_highlight_to_media_assets
Create Date: 2026-05-21 10:29:48.690435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78dfff32aa3'
down_revision: Union[str, Sequence[str], None] = 'add_is_highlight_to_media_assets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
